######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 1 22:24:41 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += network

# Input
HEADERS += UdpReceive.h
SOURCES += main.cpp UdpReceive.cpp
