######################################################################
# Automatically generated by qmake (1.07a) Mon Nov 1 22:17:52 2010
######################################################################

TEMPLATE = app
INCLUDEPATH += .


QT += network

# Input
HEADERS += UdpSend.h
SOURCES += main.cpp UdpSend.cpp
