######################################################################
# Automatically generated by qmake (1.07a) Tue Nov 2 10:53:44 2010
######################################################################

TEMPLATE = app
INCLUDEPATH += .

QT += network

# Input
HEADERS += ImageReceiver.h
SOURCES += ImageReceiver.cpp main.cpp
