######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 2 10:29:20 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += network

# Input
HEADERS += ImageServer.h
SOURCES += ImageServer.cpp main.cpp


QT += multimedia


# Input
HEADERS += ../../VideoFrame.h 
	
	
SOURCES += ../../VideoFrame.cpp

unix {
	HEADERS += \
		../../SimpleV4L2.h
	SOURCES += \
		../../SimpleV4L2.cpp
}
