######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 1 16:35:10 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += WarpTest1.cpp

DEFINES += OPENCV_ENABLED
LIBS += -L/usr/local/lib -lcv -lcxcore -lhighgui

INCLUDEPATH += /usr/include/opencv